languageCode = "en"
languageName = "English"
weight = 1

title = "nikita.computer"
copyright = "The content for this site is [CC-BY 2.0](https://creativecommons.org/licenses/by/2.0/), the [code](https://github.com/nikitawootten/nikitawootten.github.io) is [MIT](https://github.com/nikitawootten/nikitawootten.github.io/blob/main/LICENSE)"

[params.author]
name = "Nikita Wootten"
image = "img/lucya.png"
headline = "**{insert programming language}** tolerator, DevOps and InfoSec practitioner, and homelab hobbyist"
# bio = "A little bit about you"
links = [
  { email = "mailto:stdin@nikita.computer" },
  { github = "https://github.com/nikitawootten" },
  { linkedin = "https://www.linkedin.com/in/nikita-wootten/" },
  { mastodon = "https://mstdn.social/@nikitaw" },
]
