baseURL: https://nikita.computer
languageCode: en-us
title: nikita.computer
author:
  name: Nikita Wootten
permalinks:
  posts: /posts/:year-:month-:day-:filename
taxonomies:
  tag: tags
params:
  dateFormat: Jan 2, 2006
  license: The content for this site is [CC-BY 2.0](https://creativecommons.org/licenses/by/2.0/), the [code](https://github.com/nikitawootten/nikitawootten.github.io) is [MIT](https://github.com/nikitawootten/nikitawootten.github.io/blob/main/LICENSE)
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
markup:
  highlight:
    lineNos: true
    codeFences: true
    noClasses: true
    style: murphy
