baseURL: https://nikita.computer
languageCode: en-us
title: Hugo Blog
author:
  name: Nikita Wootten
permalinks:
  posts: /posts/:year-:month-:day-:filename
taxonomies:
  tag: tags
params:
  dateFormat: Jan 2, 2006
  homeText: A hugo blog
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
markup:
  highlight:
    lineNos: true
    codeFences: true
    noClasses: true
    style: murphy
